-- Seed técnico de horóscopos (DEMOSTRACIÓN)
-- Uso: ejecutar manualmente en entornos de desarrollo.
-- NO ejecutar automáticamente en producción.
-- Marca cada fila con is_demo = true para poder filtrarlas o eliminarlas.

INSERT INTO public.horoscopes
  (sign_slug, period, date_for, summary, focus, mood, energy, love, work, wellbeing, lucky_number, lucky_color, is_demo, published_at)
VALUES
  ('aries','daily', CURRENT_DATE, 'Ordena tus prioridades antes de actuar. El día favorece conversaciones directas si dejas espacio para escuchar.', 'Claridad', 'Movimiento', 4, 'Un gesto sencillo abre una conversación pendiente.', 'Avanza en algo pequeño antes de comprometerte con más.', 'Camina sin auriculares diez minutos.', 7, 'Coral', true, now()),
  ('tauro','daily', CURRENT_DATE, 'Vuelve a lo que te sostiene. La constancia de hoy prepara el terreno para decisiones más grandes esta semana.', 'Constancia', 'Serenidad', 3, 'Detalles sencillos generan más cercanía que las palabras.', 'Ordena lo tuyo antes de sumar tareas nuevas.', 'Come sin pantallas al menos una vez.', 2, 'Verde salvia', true, now()),
  ('geminis','daily', CURRENT_DATE, 'La curiosidad se enciende. Toma nota de las ideas que aparecen sin descartar ninguna todavía.', 'Curiosidad', 'Ligereza', 4, 'Escribir antes de hablar te ahorra malentendidos.', 'Elige una sola idea y trabájala a fondo.', 'Alterna concentración y movimiento breve.', 5, 'Amarillo suave', true, now()),
  ('cancer','daily', CURRENT_DATE, 'Cuida lo que sientes sin cerrarte al mundo. Pequeños gestos hacia ti misma marcan el tono del día.', 'Cuidado', 'Ternura', 3, 'Un mensaje sincero vale más que un plan elaborado.', 'Pon límites amables a lo que consume tu energía.', 'Bebe agua templada al despertar.', 9, 'Azul lino', true, now()),
  ('leo','daily', CURRENT_DATE, 'Tu presencia contagia. Comparte lo que estás creando, aunque aún no esté perfecto.', 'Expresión', 'Confianza', 5, 'Un cumplido honesto abre más de lo que imaginas.', 'Muestra un avance en lugar de esperar el resultado final.', 'Cinco minutos de sol al despertar.', 1, 'Ámbar', true, now()),
  ('virgo','daily', CURRENT_DATE, 'Ajusta lo que ya funciona en lugar de reinventarlo. Hoy el orden se convierte en energía.', 'Orden', 'Enfoque', 4, 'Pregunta cómo puedes ayudar sin dar por sentado nada.', 'Cierra ciclos abiertos antes de empezar tareas nuevas.', 'Estira la espalda cada dos horas.', 6, 'Ocre', true, now()),
  ('libra','daily', CURRENT_DATE, 'Busca el punto medio sin renunciar a lo que necesitas. Elegir también es una forma de cuidar.', 'Equilibrio', 'Diplomacia', 3, 'Di lo que piensas con suavidad, pero dilo.', 'Prioriza una decisión que llevas postergando.', 'Camina descalza cinco minutos sobre una superficie natural.', 6, 'Rosa palo', true, now()),
  ('escorpio','daily', CURRENT_DATE, 'Menos palabras y más profundidad. Confía en lo que intuyes, aunque aún no puedas explicarlo del todo.', 'Intuición', 'Intensidad', 4, 'Escuchar en silencio dice más que responder rápido.', 'Investiga antes de responder a una propuesta importante.', 'Respiración lenta antes de dormir.', 8, 'Vino tinto', true, now()),
  ('sagitario','daily', CURRENT_DATE, 'Un aire nuevo llega si te atreves a mover algo pequeño. La aventura empieza en lo cotidiano.', 'Aventura', 'Optimismo', 5, 'Propón un plan diferente al de siempre.', 'Aprende algo breve que no tenga que ver con tu trabajo.', 'Estírate al aire libre aunque sean minutos.', 3, 'Turquesa', true, now()),
  ('capricornio','daily', CURRENT_DATE, 'Los avances discretos son los más duraderos. Confía en el paso a paso que ya estás construyendo.', 'Estrategia', 'Disciplina', 4, 'Detalles constantes construyen la confianza que buscas.', 'Divide una meta grande en tres acciones concretas.', 'Duerme veinte minutos antes de lo habitual.', 4, 'Gris pizarra', true, now()),
  ('acuario','daily', CURRENT_DATE, 'Ideas nuevas piden espacio. Anótalas antes de someterlas al juicio de nadie.', 'Innovación', 'Independencia', 4, 'Comparte una idea sin esperar aprobación inmediata.', 'Prueba una forma distinta de resolver algo repetitivo.', 'Pausas breves lejos de la pantalla.', 11, 'Azul eléctrico', true, now()),
  ('piscis','daily', CURRENT_DATE, 'Suaviza el ritmo. Lo que necesitas resolver hoy se aclara si te das un momento para respirar.', 'Sensibilidad', 'Calma', 3, 'Un abrazo o una llamada breve reordenan el día.', 'Concéntrate en una sola tarea con música que te acompañe.', 'Baño tibio o pies en agua templada.', 12, 'Lavanda', true, now())
ON CONFLICT (sign_slug, period, date_for) DO NOTHING;
