/**
 * Registro único de iconos de interfaz — Migrado a Hugeicons.
 * Usar solo nombres verificados en @hugeicons/core-free-icons.
 */

import {
  AlertCircleIcon,
  ArrowReloadHorizontalIcon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  BookOpen01Icon,
  BubbleChatIcon,
  BulbIcon,
  Calendar03Icon,
  CancelCircleIcon,
  Cards02Icon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleDotIcon,
  CircleIcon,
  Clock03Icon,
  FavouriteIcon,
  GibbousMoonIcon,
  GitBranchIcon,
  GripVerticalIcon,
  HeartIcon,
  Home01Icon,
  Login01Icon,
  Logout01Icon,
  Mail01Icon,
  Menu01Icon,
  MinusSignIcon,
  Moon02Icon,
  MoonCloudIcon,
  MoonEclipseIcon,
  MoonFastWindIcon,
  MoonIcon,
  MoonSlowWindIcon,
  MoreHorizontalIcon,
  Notification03Icon,
  PanelLeftIcon,
  Search01Icon,
  Settings01Icon,
  Share01Icon,
  SparklesIcon,
  StarsIcon,
  Sun03Icon,
  UserIcon,
  ViewIcon,
  ViewOffSlashIcon,
} from "@hugeicons/core-free-icons";

export const iconRegistry = {
  search: Search01Icon,
  home: Home01Icon,
  user: UserIcon,
  account: UserIcon,
  notification: Notification03Icon,
  close: CancelCircleIcon,
  eye: ViewIcon,
  eyeOff: ViewOffSlashIcon,
  moon: Moon02Icon,
  sun: Sun03Icon,

  menu: Menu01Icon,
  back: ArrowLeft01Icon,
  arrowLeft: ArrowLeft01Icon,
  forward: ArrowRight01Icon,
  "arrow-right": ArrowRight01Icon,
  login: Login01Icon,
  logout: Logout01Icon,
  favorite: FavouriteIcon,
  history: Clock03Icon,
  calendar: Calendar03Icon,
  share: Share01Icon,
  settings: Settings01Icon,
  email: Mail01Icon,
  premium: StarsIcon,
  tarot: Cards02Icon,
  compatibility: HeartIcon,
  heart: HeartIcon,
  article: BookOpen01Icon,
  warning: AlertCircleIcon,
  expand: ChevronDownIcon,
  chevronRight: ChevronRightIcon,
  chevronLeft: ChevronLeftIcon,
  chevronUp: ChevronUpIcon,
  check: CheckIcon,
  circle: CircleIcon,
  circleDot: CircleDotIcon,
  moreHorizontal: MoreHorizontalIcon,
  minus: MinusSignIcon,
  gripVertical: GripVerticalIcon,
  panelLeft: PanelLeftIcon,
  sparkles: SparklesIcon,
  alertCircle: AlertCircleIcon,
  message: BubbleChatIcon,
  reset: ArrowReloadHorizontalIcon,
  gitBranch: GitBranchIcon,
  lightbulb: BulbIcon,

  moon_new: MoonEclipseIcon,
  moon_waxing_crescent: Moon02Icon,
  moon_first_quarter: MoonIcon,
  moon_waxing_gibbous: GibbousMoonIcon,
  moon_full: CircleIcon,
  moon_waning_gibbous: MoonCloudIcon,
  moon_last_quarter: MoonSlowWindIcon,
  moon_waning_crescent: MoonFastWindIcon,
} as const;

export type IconName = keyof typeof iconRegistry;

export const iconSizes = {
  xs: 14,
  sm: 16,
  md: 20,
  lg: 24,
  xl: 32,
} as const;

export const iconStroke = {
  default: 1.5,
  decorative: 1.25,
} as const;
