/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AvisoDeResponsabilidadRouteImport } from './routes/aviso-de-responsabilidad'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LunaRouteImport } from './routes/luna'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TemasRouteImport } from './routes/temas'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedMiEspacioRouteImport } from './routes/_authenticated/mi-espacio'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AstrologiaIndexRouteImport } from './routes/astrologia.index'
import { Route as AstrologiaAscendenteRouteImport } from './routes/astrologia.ascendente'
import { Route as AstrologiaCartaNatalRouteImport } from './routes/astrologia.carta-natal'
import { Route as AstrologiaSignoLunarRouteImport } from './routes/astrologia.signo-lunar'
import { Route as AstrologiaSinastriaRouteImport } from './routes/astrologia.sinastria'
import { Route as AstrologiaTransitosRouteImport } from './routes/astrologia.transitos'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AutoresSlugRouteImport } from './routes/autores.$slug'
import { Route as CompatibilidadIndexRouteImport } from './routes/compatibilidad.index'
import { Route as GuiasIndexRouteImport } from './routes/guias.index'
import { Route as GuiasSlugRouteImport } from './routes/guias.$slug'
import { Route as HoroscopoIndexRouteImport } from './routes/horoscopo.index'
import { Route as HoroscopoSignRouteImport } from './routes/horoscopo.$sign'
import { Route as HoroscopoHoyRouteImport } from './routes/horoscopo.hoy'
import { Route as HoroscopoMesRouteImport } from './routes/horoscopo.mes'
import { Route as HoroscopoSemanaRouteImport } from './routes/horoscopo.semana'
import { Route as LunaCalendarioRouteImport } from './routes/luna.calendario'
import { Route as LunaFasesRouteImport } from './routes/luna.fases'
import { Route as LunaHoyRouteImport } from './routes/luna.hoy'
import { Route as NewsletterUnsubscribeRouteImport } from './routes/newsletter.unsubscribe'
import { Route as NumerologiaCaminoDeVidaRouteImport } from './routes/numerologia.camino-de-vida'
import { Route as PerfilUsernameRouteImport } from './routes/perfil.$username'
import { Route as TarotIndexRouteImport } from './routes/tarot.index'
import { Route as TarotCartaDelDiaRouteImport } from './routes/tarot.carta-del-dia'
import { Route as TarotDecisionRouteImport } from './routes/tarot.decision'
import { Route as TarotSiONoRouteImport } from './routes/tarot.si-o-no'
import { Route as TarotTresCartasRouteImport } from './routes/tarot.tres-cartas'
import { Route as TemasCategoryRouteImport } from './routes/temas.$category'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminArticulosRouteImport } from './routes/_authenticated/admin/articulos'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'
import { Route as AuthenticatedAdminComunidadRouteImport } from './routes/_authenticated/admin/comunidad'
import { Route as AuthenticatedMiEspacioConfiguracionRouteImport } from './routes/_authenticated/mi-espacio.configuracion'
import { Route as AuthenticatedMiEspacioFavoritosRouteImport } from './routes/_authenticated/mi-espacio.favoritos'
import { Route as AuthenticatedMiEspacioHistorialRouteImport } from './routes/_authenticated/mi-espacio.historial'
import { Route as AuthenticatedMiEspacioLecturasRouteImport } from './routes/_authenticated/mi-espacio.lecturas'
import { Route as AuthenticatedMiEspacioMemoriaRouteImport } from './routes/_authenticated/mi-espacio.memoria'
import { Route as AuthenticatedMiEspacioPerfilRouteImport } from './routes/_authenticated/mi-espacio.perfil'
import { Route as AuthenticatedMiEspacioPrivacidadRouteImport } from './routes/_authenticated/mi-espacio.privacidad'
import { Route as AuthenticatedMiEspacioPublicacionesRouteImport } from './routes/_authenticated/mi-espacio.publicaciones'
import { Route as ApiAiRespondRouteImport } from './routes/api/ai/respond'
import { Route as ApiSearchSuggestionsRouteImport } from './routes/api/search/suggestions'
import { Route as CompatibilidadSignASignBRouteImport } from './routes/compatibilidad.$signA.$signB'
import { Route as LunaCalendarioYmRouteImport } from './routes/luna.calendario.$ym'
import { Route as LunaFasesSlugRouteImport } from './routes/luna.fases.$slug'
import { Route as TarotCartasIndexRouteImport } from './routes/tarot.cartas.index'
import { Route as TarotCartasCardRouteImport } from './routes/tarot.cartas.$card'
import { Route as AuthenticatedAdminArticulosIdRouteImport } from './routes/_authenticated/admin/articulos.$id'
import { Route as AuthenticatedAdminArticulosNuevoRouteImport } from './routes/_authenticated/admin/articulos.nuevo'
import { Route as AuthenticatedAdminArticulosIdPreviewRouteImport } from './routes/_authenticated/admin/articulos.$id.preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDeResponsabilidadRoute = AvisoDeResponsabilidadRouteImport.update({
  id: '/aviso-de-responsabilidad',
  path: '/aviso-de-responsabilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LunaRoute = LunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasRoute = TemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiEspacioRoute = AuthenticatedMiEspacioRouteImport.update({
  id: '/mi-espacio',
  path: '/mi-espacio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologiaIndexRoute = AstrologiaIndexRouteImport.update({
  id: '/astrologia/',
  path: '/astrologia/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologiaAscendenteRoute = AstrologiaAscendenteRouteImport.update({
  id: '/astrologia/ascendente',
  path: '/astrologia/ascendente',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologiaCartaNatalRoute = AstrologiaCartaNatalRouteImport.update({
  id: '/astrologia/carta-natal',
  path: '/astrologia/carta-natal',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologiaSignoLunarRoute = AstrologiaSignoLunarRouteImport.update({
  id: '/astrologia/signo-lunar',
  path: '/astrologia/signo-lunar',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologiaSinastriaRoute = AstrologiaSinastriaRouteImport.update({
  id: '/astrologia/sinastria',
  path: '/astrologia/sinastria',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologiaTransitosRoute = AstrologiaTransitosRouteImport.update({
  id: '/astrologia/transitos',
  path: '/astrologia/transitos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AutoresSlugRoute = AutoresSlugRouteImport.update({
  id: '/autores/$slug',
  path: '/autores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilidadIndexRoute = CompatibilidadIndexRouteImport.update({
  id: '/compatibilidad/',
  path: '/compatibilidad/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasIndexRoute = GuiasIndexRouteImport.update({
  id: '/guias/',
  path: '/guias/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasSlugRoute = GuiasSlugRouteImport.update({
  id: '/guias/$slug',
  path: '/guias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopoIndexRoute = HoroscopoIndexRouteImport.update({
  id: '/horoscopo/',
  path: '/horoscopo/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopoSignRoute = HoroscopoSignRouteImport.update({
  id: '/horoscopo/$sign',
  path: '/horoscopo/$sign',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopoHoyRoute = HoroscopoHoyRouteImport.update({
  id: '/horoscopo/hoy',
  path: '/horoscopo/hoy',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopoMesRoute = HoroscopoMesRouteImport.update({
  id: '/horoscopo/mes',
  path: '/horoscopo/mes',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopoSemanaRoute = HoroscopoSemanaRouteImport.update({
  id: '/horoscopo/semana',
  path: '/horoscopo/semana',
  getParentRoute: () => rootRouteImport,
} as any)
const LunaCalendarioRoute = LunaCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => LunaRoute,
} as any)
const LunaFasesRoute = LunaFasesRouteImport.update({
  id: '/fases',
  path: '/fases',
  getParentRoute: () => LunaRoute,
} as any)
const LunaHoyRoute = LunaHoyRouteImport.update({
  id: '/hoy',
  path: '/hoy',
  getParentRoute: () => LunaRoute,
} as any)
const NewsletterUnsubscribeRoute = NewsletterUnsubscribeRouteImport.update({
  id: '/newsletter/unsubscribe',
  path: '/newsletter/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologiaCaminoDeVidaRoute = NumerologiaCaminoDeVidaRouteImport.update({
  id: '/numerologia/camino-de-vida',
  path: '/numerologia/camino-de-vida',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilUsernameRoute = PerfilUsernameRouteImport.update({
  id: '/perfil/$username',
  path: '/perfil/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotIndexRoute = TarotIndexRouteImport.update({
  id: '/tarot/',
  path: '/tarot/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotCartaDelDiaRoute = TarotCartaDelDiaRouteImport.update({
  id: '/tarot/carta-del-dia',
  path: '/tarot/carta-del-dia',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotDecisionRoute = TarotDecisionRouteImport.update({
  id: '/tarot/decision',
  path: '/tarot/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotSiONoRoute = TarotSiONoRouteImport.update({
  id: '/tarot/si-o-no',
  path: '/tarot/si-o-no',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotTresCartasRoute = TarotTresCartasRouteImport.update({
  id: '/tarot/tres-cartas',
  path: '/tarot/tres-cartas',
  getParentRoute: () => rootRouteImport,
} as any)
const TemasCategoryRoute = TemasCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => TemasRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminArticulosRoute =
  AuthenticatedAdminArticulosRouteImport.update({
    id: '/articulos',
    path: '/articulos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminComunidadRoute =
  AuthenticatedAdminComunidadRouteImport.update({
    id: '/comunidad',
    path: '/comunidad',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedMiEspacioConfiguracionRoute =
  AuthenticatedMiEspacioConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedMiEspacioRoute,
  } as any)
const AuthenticatedMiEspacioFavoritosRoute =
  AuthenticatedMiEspacioFavoritosRouteImport.update({
    id: '/favoritos',
    path: '/favoritos',
    getParentRoute: () => AuthenticatedMiEspacioRoute,
  } as any)
const AuthenticatedMiEspacioHistorialRoute =
  AuthenticatedMiEspacioHistorialRouteImport.update({
    id: '/historial',
    path: '/historial',
    getParentRoute: () => AuthenticatedMiEspacioRoute,
  } as any)
const AuthenticatedMiEspacioLecturasRoute =
  AuthenticatedMiEspacioLecturasRouteImport.update({
    id: '/lecturas',
    path: '/lecturas',
    getParentRoute: () => AuthenticatedMiEspacioRoute,
  } as any)
const AuthenticatedMiEspacioMemoriaRoute =
  AuthenticatedMiEspacioMemoriaRouteImport.update({
    id: '/memoria',
    path: '/memoria',
    getParentRoute: () => AuthenticatedMiEspacioRoute,
  } as any)
const AuthenticatedMiEspacioPerfilRoute =
  AuthenticatedMiEspacioPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedMiEspacioRoute,
  } as any)
const AuthenticatedMiEspacioPrivacidadRoute =
  AuthenticatedMiEspacioPrivacidadRouteImport.update({
    id: '/privacidad',
    path: '/privacidad',
    getParentRoute: () => AuthenticatedMiEspacioRoute,
  } as any)
const AuthenticatedMiEspacioPublicacionesRoute =
  AuthenticatedMiEspacioPublicacionesRouteImport.update({
    id: '/publicaciones',
    path: '/publicaciones',
    getParentRoute: () => AuthenticatedMiEspacioRoute,
  } as any)
const ApiAiRespondRoute = ApiAiRespondRouteImport.update({
  id: '/api/ai/respond',
  path: '/api/ai/respond',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchSuggestionsRoute = ApiSearchSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => ApiSearchRoute,
} as any)
const CompatibilidadSignASignBRoute =
  CompatibilidadSignASignBRouteImport.update({
    id: '/compatibilidad/$signA/$signB',
    path: '/compatibilidad/$signA/$signB',
    getParentRoute: () => rootRouteImport,
  } as any)
const LunaCalendarioYmRoute = LunaCalendarioYmRouteImport.update({
  id: '/$ym',
  path: '/$ym',
  getParentRoute: () => LunaCalendarioRoute,
} as any)
const LunaFasesSlugRoute = LunaFasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LunaFasesRoute,
} as any)
const TarotCartasIndexRoute = TarotCartasIndexRouteImport.update({
  id: '/tarot/cartas/',
  path: '/tarot/cartas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotCartasCardRoute = TarotCartasCardRouteImport.update({
  id: '/tarot/cartas/$card',
  path: '/tarot/cartas/$card',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminArticulosIdRoute =
  AuthenticatedAdminArticulosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminArticulosRoute,
  } as any)
const AuthenticatedAdminArticulosNuevoRoute =
  AuthenticatedAdminArticulosNuevoRouteImport.update({
    id: '/nuevo',
    path: '/nuevo',
    getParentRoute: () => AuthenticatedAdminArticulosRoute,
  } as any)
const AuthenticatedAdminArticulosIdPreviewRoute =
  AuthenticatedAdminArticulosIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedAdminArticulosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/auth': typeof AuthRouteWithChildren
  '/aviso-de-responsabilidad': typeof AvisoDeResponsabilidadRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/comunidad': typeof ComunidadRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/design-system': typeof DesignSystemRoute
  '/luna': typeof LunaRouteWithChildren
  '/metodo': typeof MetodoRoute
  '/nosotros': typeof NosotrosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/temas': typeof TemasRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/mi-espacio': typeof AuthenticatedMiEspacioRouteWithChildren
  '/api/search': typeof ApiSearchRouteWithChildren
  '/astrologia/ascendente': typeof AstrologiaAscendenteRoute
  '/astrologia/carta-natal': typeof AstrologiaCartaNatalRoute
  '/astrologia/signo-lunar': typeof AstrologiaSignoLunarRoute
  '/astrologia/sinastria': typeof AstrologiaSinastriaRoute
  '/astrologia/transitos': typeof AstrologiaTransitosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/autores/$slug': typeof AutoresSlugRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/horoscopo/$sign': typeof HoroscopoSignRoute
  '/horoscopo/hoy': typeof HoroscopoHoyRoute
  '/horoscopo/mes': typeof HoroscopoMesRoute
  '/horoscopo/semana': typeof HoroscopoSemanaRoute
  '/luna/calendario': typeof LunaCalendarioRouteWithChildren
  '/luna/fases': typeof LunaFasesRouteWithChildren
  '/luna/hoy': typeof LunaHoyRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/numerologia/camino-de-vida': typeof NumerologiaCaminoDeVidaRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/tarot/carta-del-dia': typeof TarotCartaDelDiaRoute
  '/tarot/decision': typeof TarotDecisionRoute
  '/tarot/si-o-no': typeof TarotSiONoRoute
  '/tarot/tres-cartas': typeof TarotTresCartasRoute
  '/temas/$category': typeof TemasCategoryRoute
  '/astrologia/': typeof AstrologiaIndexRoute
  '/compatibilidad/': typeof CompatibilidadIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/horoscopo/': typeof HoroscopoIndexRoute
  '/tarot/': typeof TarotIndexRoute
  '/admin/articulos': typeof AuthenticatedAdminArticulosRouteWithChildren
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/comunidad': typeof AuthenticatedAdminComunidadRoute
  '/mi-espacio/configuracion': typeof AuthenticatedMiEspacioConfiguracionRoute
  '/mi-espacio/favoritos': typeof AuthenticatedMiEspacioFavoritosRoute
  '/mi-espacio/historial': typeof AuthenticatedMiEspacioHistorialRoute
  '/mi-espacio/lecturas': typeof AuthenticatedMiEspacioLecturasRoute
  '/mi-espacio/memoria': typeof AuthenticatedMiEspacioMemoriaRoute
  '/mi-espacio/perfil': typeof AuthenticatedMiEspacioPerfilRoute
  '/mi-espacio/privacidad': typeof AuthenticatedMiEspacioPrivacidadRoute
  '/mi-espacio/publicaciones': typeof AuthenticatedMiEspacioPublicacionesRoute
  '/api/ai/respond': typeof ApiAiRespondRoute
  '/api/search/suggestions': typeof ApiSearchSuggestionsRoute
  '/compatibilidad/$signA/$signB': typeof CompatibilidadSignASignBRoute
  '/luna/calendario/$ym': typeof LunaCalendarioYmRoute
  '/luna/fases/$slug': typeof LunaFasesSlugRoute
  '/tarot/cartas/$card': typeof TarotCartasCardRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/tarot/cartas/': typeof TarotCartasIndexRoute
  '/admin/articulos/$id': typeof AuthenticatedAdminArticulosIdRouteWithChildren
  '/admin/articulos/nuevo': typeof AuthenticatedAdminArticulosNuevoRoute
  '/admin/articulos/$id/preview': typeof AuthenticatedAdminArticulosIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/auth': typeof AuthRouteWithChildren
  '/aviso-de-responsabilidad': typeof AvisoDeResponsabilidadRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/comunidad': typeof ComunidadRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/design-system': typeof DesignSystemRoute
  '/luna': typeof LunaRouteWithChildren
  '/metodo': typeof MetodoRoute
  '/nosotros': typeof NosotrosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/temas': typeof TemasRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/mi-espacio': typeof AuthenticatedMiEspacioRouteWithChildren
  '/api/search': typeof ApiSearchRouteWithChildren
  '/astrologia/ascendente': typeof AstrologiaAscendenteRoute
  '/astrologia/carta-natal': typeof AstrologiaCartaNatalRoute
  '/astrologia/signo-lunar': typeof AstrologiaSignoLunarRoute
  '/astrologia/sinastria': typeof AstrologiaSinastriaRoute
  '/astrologia/transitos': typeof AstrologiaTransitosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/autores/$slug': typeof AutoresSlugRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/horoscopo/$sign': typeof HoroscopoSignRoute
  '/horoscopo/hoy': typeof HoroscopoHoyRoute
  '/horoscopo/mes': typeof HoroscopoMesRoute
  '/horoscopo/semana': typeof HoroscopoSemanaRoute
  '/luna/calendario': typeof LunaCalendarioRouteWithChildren
  '/luna/fases': typeof LunaFasesRouteWithChildren
  '/luna/hoy': typeof LunaHoyRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/numerologia/camino-de-vida': typeof NumerologiaCaminoDeVidaRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/tarot/carta-del-dia': typeof TarotCartaDelDiaRoute
  '/tarot/decision': typeof TarotDecisionRoute
  '/tarot/si-o-no': typeof TarotSiONoRoute
  '/tarot/tres-cartas': typeof TarotTresCartasRoute
  '/temas/$category': typeof TemasCategoryRoute
  '/astrologia': typeof AstrologiaIndexRoute
  '/compatibilidad': typeof CompatibilidadIndexRoute
  '/guias': typeof GuiasIndexRoute
  '/horoscopo': typeof HoroscopoIndexRoute
  '/tarot': typeof TarotIndexRoute
  '/admin/articulos': typeof AuthenticatedAdminArticulosRouteWithChildren
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/comunidad': typeof AuthenticatedAdminComunidadRoute
  '/mi-espacio/configuracion': typeof AuthenticatedMiEspacioConfiguracionRoute
  '/mi-espacio/favoritos': typeof AuthenticatedMiEspacioFavoritosRoute
  '/mi-espacio/historial': typeof AuthenticatedMiEspacioHistorialRoute
  '/mi-espacio/lecturas': typeof AuthenticatedMiEspacioLecturasRoute
  '/mi-espacio/memoria': typeof AuthenticatedMiEspacioMemoriaRoute
  '/mi-espacio/perfil': typeof AuthenticatedMiEspacioPerfilRoute
  '/mi-espacio/privacidad': typeof AuthenticatedMiEspacioPrivacidadRoute
  '/mi-espacio/publicaciones': typeof AuthenticatedMiEspacioPublicacionesRoute
  '/api/ai/respond': typeof ApiAiRespondRoute
  '/api/search/suggestions': typeof ApiSearchSuggestionsRoute
  '/compatibilidad/$signA/$signB': typeof CompatibilidadSignASignBRoute
  '/luna/calendario/$ym': typeof LunaCalendarioYmRoute
  '/luna/fases/$slug': typeof LunaFasesSlugRoute
  '/tarot/cartas/$card': typeof TarotCartasCardRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/tarot/cartas': typeof TarotCartasIndexRoute
  '/admin/articulos/$id': typeof AuthenticatedAdminArticulosIdRouteWithChildren
  '/admin/articulos/nuevo': typeof AuthenticatedAdminArticulosNuevoRoute
  '/admin/articulos/$id/preview': typeof AuthenticatedAdminArticulosIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/asistente': typeof AsistenteRoute
  '/auth': typeof AuthRouteWithChildren
  '/aviso-de-responsabilidad': typeof AvisoDeResponsabilidadRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/comunidad': typeof ComunidadRoute
  '/contacto': typeof ContactoRoute
  '/cookies': typeof CookiesRoute
  '/design-system': typeof DesignSystemRoute
  '/luna': typeof LunaRouteWithChildren
  '/metodo': typeof MetodoRoute
  '/nosotros': typeof NosotrosRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/temas': typeof TemasRouteWithChildren
  '/terminos': typeof TerminosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/mi-espacio': typeof AuthenticatedMiEspacioRouteWithChildren
  '/api/search': typeof ApiSearchRouteWithChildren
  '/astrologia/ascendente': typeof AstrologiaAscendenteRoute
  '/astrologia/carta-natal': typeof AstrologiaCartaNatalRoute
  '/astrologia/signo-lunar': typeof AstrologiaSignoLunarRoute
  '/astrologia/sinastria': typeof AstrologiaSinastriaRoute
  '/astrologia/transitos': typeof AstrologiaTransitosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/autores/$slug': typeof AutoresSlugRoute
  '/guias/$slug': typeof GuiasSlugRoute
  '/horoscopo/$sign': typeof HoroscopoSignRoute
  '/horoscopo/hoy': typeof HoroscopoHoyRoute
  '/horoscopo/mes': typeof HoroscopoMesRoute
  '/horoscopo/semana': typeof HoroscopoSemanaRoute
  '/luna/calendario': typeof LunaCalendarioRouteWithChildren
  '/luna/fases': typeof LunaFasesRouteWithChildren
  '/luna/hoy': typeof LunaHoyRoute
  '/newsletter/unsubscribe': typeof NewsletterUnsubscribeRoute
  '/numerologia/camino-de-vida': typeof NumerologiaCaminoDeVidaRoute
  '/perfil/$username': typeof PerfilUsernameRoute
  '/tarot/carta-del-dia': typeof TarotCartaDelDiaRoute
  '/tarot/decision': typeof TarotDecisionRoute
  '/tarot/si-o-no': typeof TarotSiONoRoute
  '/tarot/tres-cartas': typeof TarotTresCartasRoute
  '/temas/$category': typeof TemasCategoryRoute
  '/astrologia/': typeof AstrologiaIndexRoute
  '/compatibilidad/': typeof CompatibilidadIndexRoute
  '/guias/': typeof GuiasIndexRoute
  '/horoscopo/': typeof HoroscopoIndexRoute
  '/tarot/': typeof TarotIndexRoute
  '/_authenticated/admin/articulos': typeof AuthenticatedAdminArticulosRouteWithChildren
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/comunidad': typeof AuthenticatedAdminComunidadRoute
  '/_authenticated/mi-espacio/configuracion': typeof AuthenticatedMiEspacioConfiguracionRoute
  '/_authenticated/mi-espacio/favoritos': typeof AuthenticatedMiEspacioFavoritosRoute
  '/_authenticated/mi-espacio/historial': typeof AuthenticatedMiEspacioHistorialRoute
  '/_authenticated/mi-espacio/lecturas': typeof AuthenticatedMiEspacioLecturasRoute
  '/_authenticated/mi-espacio/memoria': typeof AuthenticatedMiEspacioMemoriaRoute
  '/_authenticated/mi-espacio/perfil': typeof AuthenticatedMiEspacioPerfilRoute
  '/_authenticated/mi-espacio/privacidad': typeof AuthenticatedMiEspacioPrivacidadRoute
  '/_authenticated/mi-espacio/publicaciones': typeof AuthenticatedMiEspacioPublicacionesRoute
  '/api/ai/respond': typeof ApiAiRespondRoute
  '/api/search/suggestions': typeof ApiSearchSuggestionsRoute
  '/compatibilidad/$signA/$signB': typeof CompatibilidadSignASignBRoute
  '/luna/calendario/$ym': typeof LunaCalendarioYmRoute
  '/luna/fases/$slug': typeof LunaFasesSlugRoute
  '/tarot/cartas/$card': typeof TarotCartasCardRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/tarot/cartas/': typeof TarotCartasIndexRoute
  '/_authenticated/admin/articulos/$id': typeof AuthenticatedAdminArticulosIdRouteWithChildren
  '/_authenticated/admin/articulos/nuevo': typeof AuthenticatedAdminArticulosNuevoRoute
  '/_authenticated/admin/articulos/$id/preview': typeof AuthenticatedAdminArticulosIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asistente'
    | '/auth'
    | '/aviso-de-responsabilidad'
    | '/ayuda'
    | '/buscar'
    | '/comunidad'
    | '/contacto'
    | '/cookies'
    | '/design-system'
    | '/luna'
    | '/metodo'
    | '/nosotros'
    | '/privacidad'
    | '/reset-password'
    | '/temas'
    | '/terminos'
    | '/admin'
    | '/mi-espacio'
    | '/api/search'
    | '/astrologia/ascendente'
    | '/astrologia/carta-natal'
    | '/astrologia/signo-lunar'
    | '/astrologia/sinastria'
    | '/astrologia/transitos'
    | '/auth/callback'
    | '/autores/$slug'
    | '/guias/$slug'
    | '/horoscopo/$sign'
    | '/horoscopo/hoy'
    | '/horoscopo/mes'
    | '/horoscopo/semana'
    | '/luna/calendario'
    | '/luna/fases'
    | '/luna/hoy'
    | '/newsletter/unsubscribe'
    | '/numerologia/camino-de-vida'
    | '/perfil/$username'
    | '/tarot/carta-del-dia'
    | '/tarot/decision'
    | '/tarot/si-o-no'
    | '/tarot/tres-cartas'
    | '/temas/$category'
    | '/astrologia/'
    | '/compatibilidad/'
    | '/guias/'
    | '/horoscopo/'
    | '/tarot/'
    | '/admin/articulos'
    | '/admin/auditoria'
    | '/admin/comunidad'
    | '/mi-espacio/configuracion'
    | '/mi-espacio/favoritos'
    | '/mi-espacio/historial'
    | '/mi-espacio/lecturas'
    | '/mi-espacio/memoria'
    | '/mi-espacio/perfil'
    | '/mi-espacio/privacidad'
    | '/mi-espacio/publicaciones'
    | '/api/ai/respond'
    | '/api/search/suggestions'
    | '/compatibilidad/$signA/$signB'
    | '/luna/calendario/$ym'
    | '/luna/fases/$slug'
    | '/tarot/cartas/$card'
    | '/admin/'
    | '/tarot/cartas/'
    | '/admin/articulos/$id'
    | '/admin/articulos/nuevo'
    | '/admin/articulos/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asistente'
    | '/auth'
    | '/aviso-de-responsabilidad'
    | '/ayuda'
    | '/buscar'
    | '/comunidad'
    | '/contacto'
    | '/cookies'
    | '/design-system'
    | '/luna'
    | '/metodo'
    | '/nosotros'
    | '/privacidad'
    | '/reset-password'
    | '/temas'
    | '/terminos'
    | '/mi-espacio'
    | '/api/search'
    | '/astrologia/ascendente'
    | '/astrologia/carta-natal'
    | '/astrologia/signo-lunar'
    | '/astrologia/sinastria'
    | '/astrologia/transitos'
    | '/auth/callback'
    | '/autores/$slug'
    | '/guias/$slug'
    | '/horoscopo/$sign'
    | '/horoscopo/hoy'
    | '/horoscopo/mes'
    | '/horoscopo/semana'
    | '/luna/calendario'
    | '/luna/fases'
    | '/luna/hoy'
    | '/newsletter/unsubscribe'
    | '/numerologia/camino-de-vida'
    | '/perfil/$username'
    | '/tarot/carta-del-dia'
    | '/tarot/decision'
    | '/tarot/si-o-no'
    | '/tarot/tres-cartas'
    | '/temas/$category'
    | '/astrologia'
    | '/compatibilidad'
    | '/guias'
    | '/horoscopo'
    | '/tarot'
    | '/admin/articulos'
    | '/admin/auditoria'
    | '/admin/comunidad'
    | '/mi-espacio/configuracion'
    | '/mi-espacio/favoritos'
    | '/mi-espacio/historial'
    | '/mi-espacio/lecturas'
    | '/mi-espacio/memoria'
    | '/mi-espacio/perfil'
    | '/mi-espacio/privacidad'
    | '/mi-espacio/publicaciones'
    | '/api/ai/respond'
    | '/api/search/suggestions'
    | '/compatibilidad/$signA/$signB'
    | '/luna/calendario/$ym'
    | '/luna/fases/$slug'
    | '/tarot/cartas/$card'
    | '/admin'
    | '/tarot/cartas'
    | '/admin/articulos/$id'
    | '/admin/articulos/nuevo'
    | '/admin/articulos/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/asistente'
    | '/auth'
    | '/aviso-de-responsabilidad'
    | '/ayuda'
    | '/buscar'
    | '/comunidad'
    | '/contacto'
    | '/cookies'
    | '/design-system'
    | '/luna'
    | '/metodo'
    | '/nosotros'
    | '/privacidad'
    | '/reset-password'
    | '/temas'
    | '/terminos'
    | '/_authenticated/admin'
    | '/_authenticated/mi-espacio'
    | '/api/search'
    | '/astrologia/ascendente'
    | '/astrologia/carta-natal'
    | '/astrologia/signo-lunar'
    | '/astrologia/sinastria'
    | '/astrologia/transitos'
    | '/auth/callback'
    | '/autores/$slug'
    | '/guias/$slug'
    | '/horoscopo/$sign'
    | '/horoscopo/hoy'
    | '/horoscopo/mes'
    | '/horoscopo/semana'
    | '/luna/calendario'
    | '/luna/fases'
    | '/luna/hoy'
    | '/newsletter/unsubscribe'
    | '/numerologia/camino-de-vida'
    | '/perfil/$username'
    | '/tarot/carta-del-dia'
    | '/tarot/decision'
    | '/tarot/si-o-no'
    | '/tarot/tres-cartas'
    | '/temas/$category'
    | '/astrologia/'
    | '/compatibilidad/'
    | '/guias/'
    | '/horoscopo/'
    | '/tarot/'
    | '/_authenticated/admin/articulos'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/comunidad'
    | '/_authenticated/mi-espacio/configuracion'
    | '/_authenticated/mi-espacio/favoritos'
    | '/_authenticated/mi-espacio/historial'
    | '/_authenticated/mi-espacio/lecturas'
    | '/_authenticated/mi-espacio/memoria'
    | '/_authenticated/mi-espacio/perfil'
    | '/_authenticated/mi-espacio/privacidad'
    | '/_authenticated/mi-espacio/publicaciones'
    | '/api/ai/respond'
    | '/api/search/suggestions'
    | '/compatibilidad/$signA/$signB'
    | '/luna/calendario/$ym'
    | '/luna/fases/$slug'
    | '/tarot/cartas/$card'
    | '/_authenticated/admin/'
    | '/tarot/cartas/'
    | '/_authenticated/admin/articulos/$id'
    | '/_authenticated/admin/articulos/nuevo'
    | '/_authenticated/admin/articulos/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AsistenteRoute: typeof AsistenteRoute
  AuthRoute: typeof AuthRouteWithChildren
  AvisoDeResponsabilidadRoute: typeof AvisoDeResponsabilidadRoute
  AyudaRoute: typeof AyudaRoute
  BuscarRoute: typeof BuscarRoute
  ComunidadRoute: typeof ComunidadRoute
  ContactoRoute: typeof ContactoRoute
  CookiesRoute: typeof CookiesRoute
  DesignSystemRoute: typeof DesignSystemRoute
  LunaRoute: typeof LunaRouteWithChildren
  MetodoRoute: typeof MetodoRoute
  NosotrosRoute: typeof NosotrosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TemasRoute: typeof TemasRouteWithChildren
  TerminosRoute: typeof TerminosRoute
  ApiSearchRoute: typeof ApiSearchRouteWithChildren
  AstrologiaAscendenteRoute: typeof AstrologiaAscendenteRoute
  AstrologiaCartaNatalRoute: typeof AstrologiaCartaNatalRoute
  AstrologiaSignoLunarRoute: typeof AstrologiaSignoLunarRoute
  AstrologiaSinastriaRoute: typeof AstrologiaSinastriaRoute
  AstrologiaTransitosRoute: typeof AstrologiaTransitosRoute
  AutoresSlugRoute: typeof AutoresSlugRoute
  GuiasSlugRoute: typeof GuiasSlugRoute
  HoroscopoSignRoute: typeof HoroscopoSignRoute
  HoroscopoHoyRoute: typeof HoroscopoHoyRoute
  HoroscopoMesRoute: typeof HoroscopoMesRoute
  HoroscopoSemanaRoute: typeof HoroscopoSemanaRoute
  NewsletterUnsubscribeRoute: typeof NewsletterUnsubscribeRoute
  NumerologiaCaminoDeVidaRoute: typeof NumerologiaCaminoDeVidaRoute
  PerfilUsernameRoute: typeof PerfilUsernameRoute
  TarotCartaDelDiaRoute: typeof TarotCartaDelDiaRoute
  TarotDecisionRoute: typeof TarotDecisionRoute
  TarotSiONoRoute: typeof TarotSiONoRoute
  TarotTresCartasRoute: typeof TarotTresCartasRoute
  AstrologiaIndexRoute: typeof AstrologiaIndexRoute
  CompatibilidadIndexRoute: typeof CompatibilidadIndexRoute
  GuiasIndexRoute: typeof GuiasIndexRoute
  HoroscopoIndexRoute: typeof HoroscopoIndexRoute
  TarotIndexRoute: typeof TarotIndexRoute
  ApiAiRespondRoute: typeof ApiAiRespondRoute
  CompatibilidadSignASignBRoute: typeof CompatibilidadSignASignBRoute
  TarotCartasCardRoute: typeof TarotCartasCardRoute
  TarotCartasIndexRoute: typeof TarotCartasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-responsabilidad': {
      id: '/aviso-de-responsabilidad'
      path: '/aviso-de-responsabilidad'
      fullPath: '/aviso-de-responsabilidad'
      preLoaderRoute: typeof AvisoDeResponsabilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luna': {
      id: '/luna'
      path: '/luna'
      fullPath: '/luna'
      preLoaderRoute: typeof LunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas': {
      id: '/temas'
      path: '/temas'
      fullPath: '/temas'
      preLoaderRoute: typeof TemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-espacio': {
      id: '/_authenticated/mi-espacio'
      path: '/mi-espacio'
      fullPath: '/mi-espacio'
      preLoaderRoute: typeof AuthenticatedMiEspacioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologia/': {
      id: '/astrologia/'
      path: '/astrologia'
      fullPath: '/astrologia/'
      preLoaderRoute: typeof AstrologiaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologia/ascendente': {
      id: '/astrologia/ascendente'
      path: '/astrologia/ascendente'
      fullPath: '/astrologia/ascendente'
      preLoaderRoute: typeof AstrologiaAscendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologia/carta-natal': {
      id: '/astrologia/carta-natal'
      path: '/astrologia/carta-natal'
      fullPath: '/astrologia/carta-natal'
      preLoaderRoute: typeof AstrologiaCartaNatalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologia/signo-lunar': {
      id: '/astrologia/signo-lunar'
      path: '/astrologia/signo-lunar'
      fullPath: '/astrologia/signo-lunar'
      preLoaderRoute: typeof AstrologiaSignoLunarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologia/sinastria': {
      id: '/astrologia/sinastria'
      path: '/astrologia/sinastria'
      fullPath: '/astrologia/sinastria'
      preLoaderRoute: typeof AstrologiaSinastriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologia/transitos': {
      id: '/astrologia/transitos'
      path: '/astrologia/transitos'
      fullPath: '/astrologia/transitos'
      preLoaderRoute: typeof AstrologiaTransitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/autores/$slug': {
      id: '/autores/$slug'
      path: '/autores/$slug'
      fullPath: '/autores/$slug'
      preLoaderRoute: typeof AutoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibilidad/': {
      id: '/compatibilidad/'
      path: '/compatibilidad'
      fullPath: '/compatibilidad/'
      preLoaderRoute: typeof CompatibilidadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/': {
      id: '/guias/'
      path: '/guias'
      fullPath: '/guias/'
      preLoaderRoute: typeof GuiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias/$slug': {
      id: '/guias/$slug'
      path: '/guias/$slug'
      fullPath: '/guias/$slug'
      preLoaderRoute: typeof GuiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopo/': {
      id: '/horoscopo/'
      path: '/horoscopo'
      fullPath: '/horoscopo/'
      preLoaderRoute: typeof HoroscopoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopo/$sign': {
      id: '/horoscopo/$sign'
      path: '/horoscopo/$sign'
      fullPath: '/horoscopo/$sign'
      preLoaderRoute: typeof HoroscopoSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopo/hoy': {
      id: '/horoscopo/hoy'
      path: '/horoscopo/hoy'
      fullPath: '/horoscopo/hoy'
      preLoaderRoute: typeof HoroscopoHoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopo/mes': {
      id: '/horoscopo/mes'
      path: '/horoscopo/mes'
      fullPath: '/horoscopo/mes'
      preLoaderRoute: typeof HoroscopoMesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopo/semana': {
      id: '/horoscopo/semana'
      path: '/horoscopo/semana'
      fullPath: '/horoscopo/semana'
      preLoaderRoute: typeof HoroscopoSemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luna/calendario': {
      id: '/luna/calendario'
      path: '/calendario'
      fullPath: '/luna/calendario'
      preLoaderRoute: typeof LunaCalendarioRouteImport
      parentRoute: typeof LunaRoute
    }
    '/luna/fases': {
      id: '/luna/fases'
      path: '/fases'
      fullPath: '/luna/fases'
      preLoaderRoute: typeof LunaFasesRouteImport
      parentRoute: typeof LunaRoute
    }
    '/luna/hoy': {
      id: '/luna/hoy'
      path: '/hoy'
      fullPath: '/luna/hoy'
      preLoaderRoute: typeof LunaHoyRouteImport
      parentRoute: typeof LunaRoute
    }
    '/newsletter/unsubscribe': {
      id: '/newsletter/unsubscribe'
      path: '/newsletter/unsubscribe'
      fullPath: '/newsletter/unsubscribe'
      preLoaderRoute: typeof NewsletterUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerologia/camino-de-vida': {
      id: '/numerologia/camino-de-vida'
      path: '/numerologia/camino-de-vida'
      fullPath: '/numerologia/camino-de-vida'
      preLoaderRoute: typeof NumerologiaCaminoDeVidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$username': {
      id: '/perfil/$username'
      path: '/perfil/$username'
      fullPath: '/perfil/$username'
      preLoaderRoute: typeof PerfilUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/': {
      id: '/tarot/'
      path: '/tarot'
      fullPath: '/tarot/'
      preLoaderRoute: typeof TarotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/carta-del-dia': {
      id: '/tarot/carta-del-dia'
      path: '/tarot/carta-del-dia'
      fullPath: '/tarot/carta-del-dia'
      preLoaderRoute: typeof TarotCartaDelDiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/decision': {
      id: '/tarot/decision'
      path: '/tarot/decision'
      fullPath: '/tarot/decision'
      preLoaderRoute: typeof TarotDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/si-o-no': {
      id: '/tarot/si-o-no'
      path: '/tarot/si-o-no'
      fullPath: '/tarot/si-o-no'
      preLoaderRoute: typeof TarotSiONoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/tres-cartas': {
      id: '/tarot/tres-cartas'
      path: '/tarot/tres-cartas'
      fullPath: '/tarot/tres-cartas'
      preLoaderRoute: typeof TarotTresCartasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temas/$category': {
      id: '/temas/$category'
      path: '/$category'
      fullPath: '/temas/$category'
      preLoaderRoute: typeof TemasCategoryRouteImport
      parentRoute: typeof TemasRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/articulos': {
      id: '/_authenticated/admin/articulos'
      path: '/articulos'
      fullPath: '/admin/articulos'
      preLoaderRoute: typeof AuthenticatedAdminArticulosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/comunidad': {
      id: '/_authenticated/admin/comunidad'
      path: '/comunidad'
      fullPath: '/admin/comunidad'
      preLoaderRoute: typeof AuthenticatedAdminComunidadRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/mi-espacio/configuracion': {
      id: '/_authenticated/mi-espacio/configuracion'
      path: '/configuracion'
      fullPath: '/mi-espacio/configuracion'
      preLoaderRoute: typeof AuthenticatedMiEspacioConfiguracionRouteImport
      parentRoute: typeof AuthenticatedMiEspacioRoute
    }
    '/_authenticated/mi-espacio/favoritos': {
      id: '/_authenticated/mi-espacio/favoritos'
      path: '/favoritos'
      fullPath: '/mi-espacio/favoritos'
      preLoaderRoute: typeof AuthenticatedMiEspacioFavoritosRouteImport
      parentRoute: typeof AuthenticatedMiEspacioRoute
    }
    '/_authenticated/mi-espacio/historial': {
      id: '/_authenticated/mi-espacio/historial'
      path: '/historial'
      fullPath: '/mi-espacio/historial'
      preLoaderRoute: typeof AuthenticatedMiEspacioHistorialRouteImport
      parentRoute: typeof AuthenticatedMiEspacioRoute
    }
    '/_authenticated/mi-espacio/lecturas': {
      id: '/_authenticated/mi-espacio/lecturas'
      path: '/lecturas'
      fullPath: '/mi-espacio/lecturas'
      preLoaderRoute: typeof AuthenticatedMiEspacioLecturasRouteImport
      parentRoute: typeof AuthenticatedMiEspacioRoute
    }
    '/_authenticated/mi-espacio/memoria': {
      id: '/_authenticated/mi-espacio/memoria'
      path: '/memoria'
      fullPath: '/mi-espacio/memoria'
      preLoaderRoute: typeof AuthenticatedMiEspacioMemoriaRouteImport
      parentRoute: typeof AuthenticatedMiEspacioRoute
    }
    '/_authenticated/mi-espacio/perfil': {
      id: '/_authenticated/mi-espacio/perfil'
      path: '/perfil'
      fullPath: '/mi-espacio/perfil'
      preLoaderRoute: typeof AuthenticatedMiEspacioPerfilRouteImport
      parentRoute: typeof AuthenticatedMiEspacioRoute
    }
    '/_authenticated/mi-espacio/privacidad': {
      id: '/_authenticated/mi-espacio/privacidad'
      path: '/privacidad'
      fullPath: '/mi-espacio/privacidad'
      preLoaderRoute: typeof AuthenticatedMiEspacioPrivacidadRouteImport
      parentRoute: typeof AuthenticatedMiEspacioRoute
    }
    '/_authenticated/mi-espacio/publicaciones': {
      id: '/_authenticated/mi-espacio/publicaciones'
      path: '/publicaciones'
      fullPath: '/mi-espacio/publicaciones'
      preLoaderRoute: typeof AuthenticatedMiEspacioPublicacionesRouteImport
      parentRoute: typeof AuthenticatedMiEspacioRoute
    }
    '/api/ai/respond': {
      id: '/api/ai/respond'
      path: '/api/ai/respond'
      fullPath: '/api/ai/respond'
      preLoaderRoute: typeof ApiAiRespondRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/suggestions': {
      id: '/api/search/suggestions'
      path: '/suggestions'
      fullPath: '/api/search/suggestions'
      preLoaderRoute: typeof ApiSearchSuggestionsRouteImport
      parentRoute: typeof ApiSearchRoute
    }
    '/compatibilidad/$signA/$signB': {
      id: '/compatibilidad/$signA/$signB'
      path: '/compatibilidad/$signA/$signB'
      fullPath: '/compatibilidad/$signA/$signB'
      preLoaderRoute: typeof CompatibilidadSignASignBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luna/calendario/$ym': {
      id: '/luna/calendario/$ym'
      path: '/$ym'
      fullPath: '/luna/calendario/$ym'
      preLoaderRoute: typeof LunaCalendarioYmRouteImport
      parentRoute: typeof LunaCalendarioRoute
    }
    '/luna/fases/$slug': {
      id: '/luna/fases/$slug'
      path: '/$slug'
      fullPath: '/luna/fases/$slug'
      preLoaderRoute: typeof LunaFasesSlugRouteImport
      parentRoute: typeof LunaFasesRoute
    }
    '/tarot/cartas/': {
      id: '/tarot/cartas/'
      path: '/tarot/cartas'
      fullPath: '/tarot/cartas/'
      preLoaderRoute: typeof TarotCartasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/cartas/$card': {
      id: '/tarot/cartas/$card'
      path: '/tarot/cartas/$card'
      fullPath: '/tarot/cartas/$card'
      preLoaderRoute: typeof TarotCartasCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/articulos/$id': {
      id: '/_authenticated/admin/articulos/$id'
      path: '/$id'
      fullPath: '/admin/articulos/$id'
      preLoaderRoute: typeof AuthenticatedAdminArticulosIdRouteImport
      parentRoute: typeof AuthenticatedAdminArticulosRoute
    }
    '/_authenticated/admin/articulos/nuevo': {
      id: '/_authenticated/admin/articulos/nuevo'
      path: '/nuevo'
      fullPath: '/admin/articulos/nuevo'
      preLoaderRoute: typeof AuthenticatedAdminArticulosNuevoRouteImport
      parentRoute: typeof AuthenticatedAdminArticulosRoute
    }
    '/_authenticated/admin/articulos/$id/preview': {
      id: '/_authenticated/admin/articulos/$id/preview'
      path: '/preview'
      fullPath: '/admin/articulos/$id/preview'
      preLoaderRoute: typeof AuthenticatedAdminArticulosIdPreviewRouteImport
      parentRoute: typeof AuthenticatedAdminArticulosIdRoute
    }
  }
}

interface AuthenticatedAdminArticulosIdRouteChildren {
  AuthenticatedAdminArticulosIdPreviewRoute: typeof AuthenticatedAdminArticulosIdPreviewRoute
}

const AuthenticatedAdminArticulosIdRouteChildren: AuthenticatedAdminArticulosIdRouteChildren =
  {
    AuthenticatedAdminArticulosIdPreviewRoute:
      AuthenticatedAdminArticulosIdPreviewRoute,
  }

const AuthenticatedAdminArticulosIdRouteWithChildren =
  AuthenticatedAdminArticulosIdRoute._addFileChildren(
    AuthenticatedAdminArticulosIdRouteChildren,
  )

interface AuthenticatedAdminArticulosRouteChildren {
  AuthenticatedAdminArticulosIdRoute: typeof AuthenticatedAdminArticulosIdRouteWithChildren
  AuthenticatedAdminArticulosNuevoRoute: typeof AuthenticatedAdminArticulosNuevoRoute
}

const AuthenticatedAdminArticulosRouteChildren: AuthenticatedAdminArticulosRouteChildren =
  {
    AuthenticatedAdminArticulosIdRoute:
      AuthenticatedAdminArticulosIdRouteWithChildren,
    AuthenticatedAdminArticulosNuevoRoute:
      AuthenticatedAdminArticulosNuevoRoute,
  }

const AuthenticatedAdminArticulosRouteWithChildren =
  AuthenticatedAdminArticulosRoute._addFileChildren(
    AuthenticatedAdminArticulosRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminArticulosRoute: typeof AuthenticatedAdminArticulosRouteWithChildren
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminComunidadRoute: typeof AuthenticatedAdminComunidadRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminArticulosRoute:
      AuthenticatedAdminArticulosRouteWithChildren,
    AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
    AuthenticatedAdminComunidadRoute: AuthenticatedAdminComunidadRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedMiEspacioRouteChildren {
  AuthenticatedMiEspacioConfiguracionRoute: typeof AuthenticatedMiEspacioConfiguracionRoute
  AuthenticatedMiEspacioFavoritosRoute: typeof AuthenticatedMiEspacioFavoritosRoute
  AuthenticatedMiEspacioHistorialRoute: typeof AuthenticatedMiEspacioHistorialRoute
  AuthenticatedMiEspacioLecturasRoute: typeof AuthenticatedMiEspacioLecturasRoute
  AuthenticatedMiEspacioMemoriaRoute: typeof AuthenticatedMiEspacioMemoriaRoute
  AuthenticatedMiEspacioPerfilRoute: typeof AuthenticatedMiEspacioPerfilRoute
  AuthenticatedMiEspacioPrivacidadRoute: typeof AuthenticatedMiEspacioPrivacidadRoute
  AuthenticatedMiEspacioPublicacionesRoute: typeof AuthenticatedMiEspacioPublicacionesRoute
}

const AuthenticatedMiEspacioRouteChildren: AuthenticatedMiEspacioRouteChildren =
  {
    AuthenticatedMiEspacioConfiguracionRoute:
      AuthenticatedMiEspacioConfiguracionRoute,
    AuthenticatedMiEspacioFavoritosRoute: AuthenticatedMiEspacioFavoritosRoute,
    AuthenticatedMiEspacioHistorialRoute: AuthenticatedMiEspacioHistorialRoute,
    AuthenticatedMiEspacioLecturasRoute: AuthenticatedMiEspacioLecturasRoute,
    AuthenticatedMiEspacioMemoriaRoute: AuthenticatedMiEspacioMemoriaRoute,
    AuthenticatedMiEspacioPerfilRoute: AuthenticatedMiEspacioPerfilRoute,
    AuthenticatedMiEspacioPrivacidadRoute:
      AuthenticatedMiEspacioPrivacidadRoute,
    AuthenticatedMiEspacioPublicacionesRoute:
      AuthenticatedMiEspacioPublicacionesRoute,
  }

const AuthenticatedMiEspacioRouteWithChildren =
  AuthenticatedMiEspacioRoute._addFileChildren(
    AuthenticatedMiEspacioRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedMiEspacioRoute: typeof AuthenticatedMiEspacioRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedMiEspacioRoute: AuthenticatedMiEspacioRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LunaCalendarioRouteChildren {
  LunaCalendarioYmRoute: typeof LunaCalendarioYmRoute
}

const LunaCalendarioRouteChildren: LunaCalendarioRouteChildren = {
  LunaCalendarioYmRoute: LunaCalendarioYmRoute,
}

const LunaCalendarioRouteWithChildren = LunaCalendarioRoute._addFileChildren(
  LunaCalendarioRouteChildren,
)

interface LunaFasesRouteChildren {
  LunaFasesSlugRoute: typeof LunaFasesSlugRoute
}

const LunaFasesRouteChildren: LunaFasesRouteChildren = {
  LunaFasesSlugRoute: LunaFasesSlugRoute,
}

const LunaFasesRouteWithChildren = LunaFasesRoute._addFileChildren(
  LunaFasesRouteChildren,
)

interface LunaRouteChildren {
  LunaCalendarioRoute: typeof LunaCalendarioRouteWithChildren
  LunaFasesRoute: typeof LunaFasesRouteWithChildren
  LunaHoyRoute: typeof LunaHoyRoute
}

const LunaRouteChildren: LunaRouteChildren = {
  LunaCalendarioRoute: LunaCalendarioRouteWithChildren,
  LunaFasesRoute: LunaFasesRouteWithChildren,
  LunaHoyRoute: LunaHoyRoute,
}

const LunaRouteWithChildren = LunaRoute._addFileChildren(LunaRouteChildren)

interface TemasRouteChildren {
  TemasCategoryRoute: typeof TemasCategoryRoute
}

const TemasRouteChildren: TemasRouteChildren = {
  TemasCategoryRoute: TemasCategoryRoute,
}

const TemasRouteWithChildren = TemasRoute._addFileChildren(TemasRouteChildren)

interface ApiSearchRouteChildren {
  ApiSearchSuggestionsRoute: typeof ApiSearchSuggestionsRoute
}

const ApiSearchRouteChildren: ApiSearchRouteChildren = {
  ApiSearchSuggestionsRoute: ApiSearchSuggestionsRoute,
}

const ApiSearchRouteWithChildren = ApiSearchRoute._addFileChildren(
  ApiSearchRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AsistenteRoute: AsistenteRoute,
  AuthRoute: AuthRouteWithChildren,
  AvisoDeResponsabilidadRoute: AvisoDeResponsabilidadRoute,
  AyudaRoute: AyudaRoute,
  BuscarRoute: BuscarRoute,
  ComunidadRoute: ComunidadRoute,
  ContactoRoute: ContactoRoute,
  CookiesRoute: CookiesRoute,
  DesignSystemRoute: DesignSystemRoute,
  LunaRoute: LunaRouteWithChildren,
  MetodoRoute: MetodoRoute,
  NosotrosRoute: NosotrosRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TemasRoute: TemasRouteWithChildren,
  TerminosRoute: TerminosRoute,
  ApiSearchRoute: ApiSearchRouteWithChildren,
  AstrologiaAscendenteRoute: AstrologiaAscendenteRoute,
  AstrologiaCartaNatalRoute: AstrologiaCartaNatalRoute,
  AstrologiaSignoLunarRoute: AstrologiaSignoLunarRoute,
  AstrologiaSinastriaRoute: AstrologiaSinastriaRoute,
  AstrologiaTransitosRoute: AstrologiaTransitosRoute,
  AutoresSlugRoute: AutoresSlugRoute,
  GuiasSlugRoute: GuiasSlugRoute,
  HoroscopoSignRoute: HoroscopoSignRoute,
  HoroscopoHoyRoute: HoroscopoHoyRoute,
  HoroscopoMesRoute: HoroscopoMesRoute,
  HoroscopoSemanaRoute: HoroscopoSemanaRoute,
  NewsletterUnsubscribeRoute: NewsletterUnsubscribeRoute,
  NumerologiaCaminoDeVidaRoute: NumerologiaCaminoDeVidaRoute,
  PerfilUsernameRoute: PerfilUsernameRoute,
  TarotCartaDelDiaRoute: TarotCartaDelDiaRoute,
  TarotDecisionRoute: TarotDecisionRoute,
  TarotSiONoRoute: TarotSiONoRoute,
  TarotTresCartasRoute: TarotTresCartasRoute,
  AstrologiaIndexRoute: AstrologiaIndexRoute,
  CompatibilidadIndexRoute: CompatibilidadIndexRoute,
  GuiasIndexRoute: GuiasIndexRoute,
  HoroscopoIndexRoute: HoroscopoIndexRoute,
  TarotIndexRoute: TarotIndexRoute,
  ApiAiRespondRoute: ApiAiRespondRoute,
  CompatibilidadSignASignBRoute: CompatibilidadSignASignBRoute,
  TarotCartasCardRoute: TarotCartasCardRoute,
  TarotCartasIndexRoute: TarotCartasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
