// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function normalizeSupabaseUrl(value: string): string {
  const url = new URL(value);
  url.pathname = url.pathname.replace(/\/(?:rest|auth|storage|functions)\/v1\/?$/, "");
  return url.toString().replace(/\/$/, "");
}

function normalizeSupabaseRequestInput(input: RequestInfo | URL): RequestInfo | URL {
  const normalizeUrl = (value: string) => value.replace("/rest/v1/auth/v1/", "/auth/v1/");

  if (typeof input === "string") {
    return normalizeUrl(input);
  }

  if (input instanceof URL) {
    return new URL(normalizeUrl(input.toString()));
  }

  const normalizedUrl = normalizeUrl(input.url);
  if (normalizedUrl === input.url) return input;

  return new Request(normalizedUrl, input);
}

export function getSupabaseClientDiagnostics() {
  const rawUrl = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL || "";
  const normalizedUrl = rawUrl ? normalizeSupabaseUrl(rawUrl) : "";
  const publishableKey =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || "";

  return {
    rawUrl,
    normalizedUrl,
    authEndpoint: normalizedUrl ? `${normalizedUrl}/auth/v1` : "",
    projectRef: normalizedUrl ? new URL(normalizedUrl).hostname.split(".")[0] : "",
    keyKind: publishableKey.startsWith("sb_publishable_")
      ? "sb_publishable"
      : publishableKey.split(".").length === 3
        ? "jwt"
        : "unknown",
    hasPublishableKey: Boolean(publishableKey),
  };
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    const normalizedInput = normalizeSupabaseRequestInput(input);
    const response = await fetch(normalizedInput, { ...init, headers });
    let requestUrl: string;
    if (typeof normalizedInput === "string") {
      requestUrl = normalizedInput;
    } else if (normalizedInput instanceof URL) {
      requestUrl = normalizedInput.toString();
    } else {
      requestUrl = normalizedInput.url;
    }

    if (import.meta.env.DEV && !response.ok && requestUrl.includes("/auth/v1/")) {
      const body = await response
        .clone()
        .json()
        .catch(() => null);

      console.error("[Supabase Auth HTTP Error]", {
        status: response.status,
        statusText: response.statusText,
        url: requestUrl,
        body,
      });
    }

    return response;
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(normalizeSupabaseUrl(SUPABASE_URL), SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
